package net.arjuna.mysticalSteamAge.datagen;

import net.arjuna.mysticalSteamAge.MysticalSteamAge;
import net.arjuna.mysticalSteamAge.blocks.MysticalSteamAgeBlocksRegister;
import net.arjuna.mysticalSteamAge.blocks.MysticalSteamAgeMachinesRegister;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraftforge.common.Tags;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;

import java.util.concurrent.CompletableFuture;

public class MysticalSteamAgeBlockTags extends BlockTagsProvider {

    public MysticalSteamAgeBlockTags(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> lookupProvider, ExistingFileHelper helper) {
        super(packOutput, lookupProvider, MysticalSteamAge.MOD_ID, helper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {
        // forge
        tag(Tags.Blocks.ORES)
                .add(MysticalSteamAgeBlocksRegister.deepslate_sulphur_ore.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_tin_ore.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_zinc_ore.get())
                .add(MysticalSteamAgeBlocksRegister.nether_coal_ore.get())
                .add(MysticalSteamAgeBlocksRegister.nether_devil_iron_ore.get())
                .add(MysticalSteamAgeBlocksRegister.nether_sulphur_ore.get())
                .add(MysticalSteamAgeBlocksRegister.tin_ore.get())
                .add(MysticalSteamAgeBlocksRegister.zinc_ore.get())
                .add(MysticalSteamAgeBlocksRegister.salt_ore.get());
        tag(Tags.Blocks.STORAGE_BLOCKS)
                .add(MysticalSteamAgeBlocksRegister.brass_block.get())
                .add(MysticalSteamAgeBlocksRegister.bronze_block.get())
                .add(MysticalSteamAgeBlocksRegister.tin_block.get())
                .add(MysticalSteamAgeBlocksRegister.zinc_block.get())
                .add(MysticalSteamAgeBlocksRegister.devil_iron_block.get())
                .add(MysticalSteamAgeBlocksRegister.steel_block.get())
                .add(MysticalSteamAgeBlocksRegister.salt_block.get());
        tag(Tags.Blocks.ORES_COAL)
                .add(MysticalSteamAgeBlocksRegister.nether_coal_ore.get());
        tag(Tags.Blocks.STONE)
                .add(MysticalSteamAgeBlocksRegister.marble.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_black.get());
        tag(Tags.Blocks.FENCES_WOODEN)
                .add(MysticalSteamAgeBlocksRegister.baobab_fence.get());
        tag(Tags.Blocks.FENCE_GATES_WOODEN)
                .add(MysticalSteamAgeBlocksRegister.baobab_fence_gate.get());
        tag(MysticalSteamAgeBlocksRegister.salt_ore_tag)
                .add(MysticalSteamAgeBlocksRegister.salt_ore.get());
        tag(MysticalSteamAgeBlocksRegister.zinc_ore_tag)
                .add(MysticalSteamAgeBlocksRegister.zinc_ore.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_zinc_ore.get());
        tag(MysticalSteamAgeBlocksRegister.tin_ore_tag)
                .add(MysticalSteamAgeBlocksRegister.tin_ore.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_tin_ore.get());
        tag(MysticalSteamAgeBlocksRegister.nether_devil_iron_ore_tag)
                .add(MysticalSteamAgeBlocksRegister.nether_devil_iron_ore.get());
        tag(MysticalSteamAgeBlocksRegister.sulphur_ore_tag)
                .add(MysticalSteamAgeBlocksRegister.deepslate_sulphur_ore.get())
                .add(MysticalSteamAgeBlocksRegister.nether_sulphur_ore.get());
        tag(MysticalSteamAgeBlocksRegister.steel_block_tag)
                .add(MysticalSteamAgeBlocksRegister.steel_block.get());
        tag(MysticalSteamAgeBlocksRegister.brass_block_tag)
                .add(MysticalSteamAgeBlocksRegister.brass_block.get());
        tag(MysticalSteamAgeBlocksRegister.bronze_block_tag)
                .add(MysticalSteamAgeBlocksRegister.bronze_block.get());
        tag(MysticalSteamAgeBlocksRegister.tin_block_tag)
                .add(MysticalSteamAgeBlocksRegister.tin_block.get());
        tag(MysticalSteamAgeBlocksRegister.zinc_block_tag)
                .add(MysticalSteamAgeBlocksRegister.zinc_block.get());
        tag(MysticalSteamAgeBlocksRegister.devil_iron_block_tag)
                .add(MysticalSteamAgeBlocksRegister.devil_iron_block.get());
        tag(MysticalSteamAgeBlocksRegister.salt_block_tag)
                .add(MysticalSteamAgeBlocksRegister.salt_block.get());
        tag(MysticalSteamAgeBlocksRegister.marble_tag)
                .add(MysticalSteamAgeBlocksRegister.marble.get());
        tag(MysticalSteamAgeBlocksRegister.marble_black_tag)
                .add(MysticalSteamAgeBlocksRegister.marble_black.get());
        // Minecraft
        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(MysticalSteamAgeBlocksRegister.brass_block.get())
                .add(MysticalSteamAgeBlocksRegister.bronze_block.get())
                .add(MysticalSteamAgeBlocksRegister.tin_block.get())
                .add(MysticalSteamAgeBlocksRegister.zinc_block.get())
                .add(MysticalSteamAgeBlocksRegister.devil_iron_block.get())
                .add(MysticalSteamAgeBlocksRegister.steel_block.get())
                .add(MysticalSteamAgeBlocksRegister.salt_block.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_sulphur_ore.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_tin_ore.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_zinc_ore.get())
                .add(MysticalSteamAgeBlocksRegister.nether_coal_ore.get())
                .add(MysticalSteamAgeBlocksRegister.nether_devil_iron_ore.get())
                .add(MysticalSteamAgeBlocksRegister.nether_sulphur_ore.get())
                .add(MysticalSteamAgeBlocksRegister.tin_ore.get())
                .add(MysticalSteamAgeBlocksRegister.zinc_ore.get())
                .add(MysticalSteamAgeBlocksRegister.salt_ore.get())
                .add(MysticalSteamAgeBlocksRegister.marble.get())
                .add(MysticalSteamAgeBlocksRegister.marble_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_wall.get())
                .add(MysticalSteamAgeBlocksRegister.marble_pillar.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_slab.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_brick.get())
                .add(MysticalSteamAgeBlocksRegister.marble_bricks_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_bricks_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_bricks_wall.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_wall.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_pillar.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_black.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_black_slab.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_black_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_brick.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_bricks_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_bricks_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_bricks_wall.get())
                .add(MysticalSteamAgeBlocksRegister.sand_stone_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.marble_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.granite_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.andesite_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.diorite_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.cobblestone_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.iron_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.double_furnace.get());
        tag(BlockTags.MINEABLE_WITH_AXE)
                .add(MysticalSteamAgeBlocksRegister.oak_wardrobe.get())
                .add(MysticalSteamAgeBlocksRegister.spruce_wardrobe.get())
                .add(MysticalSteamAgeBlocksRegister.birch_wardrobe.get())
                .add(MysticalSteamAgeBlocksRegister.jungle_wardrobe.get())
                .add(MysticalSteamAgeBlocksRegister.acacia_wardrobe.get())
                .add(MysticalSteamAgeBlocksRegister.dark_oak_wardrobe.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_wardrobe.get())
                .add(MysticalSteamAgeBlocksRegister.spruce_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.oak_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.jungle_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.birch_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.dark_oak_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.acacia_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_lamp.get())
                .add(MysticalSteamAgeBlocksRegister.carpenter_workbench.get())
                .add(MysticalSteamAgeBlocksRegister.block_black_hardened_leather.get())
                .add(MysticalSteamAgeBlocksRegister.block_blue_hardened_leather.get())
                .add(MysticalSteamAgeBlocksRegister.block_brown_hardened_leather.get())
                .add(MysticalSteamAgeBlocksRegister.block_green_hardened_leather.get())
                .add(MysticalSteamAgeBlocksRegister.block_light_green_hardened_leather.get())
                .add(MysticalSteamAgeBlocksRegister.block_purple_hardened_leather.get())
                .add(MysticalSteamAgeBlocksRegister.block_red_hardened_leather.get())
                .add(MysticalSteamAgeBlocksRegister.block_white_hardened_leather.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_log.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_wood.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_planks.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_slab.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_trapdoor.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_door.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_button.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_fence.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_fence_gate.get())
                .add(MysticalSteamAgeBlocksRegister.studded_wooden_door_1.get())
                .add(MysticalSteamAgeBlocksRegister.studded_wooden_door_2.get())
                .add(MysticalSteamAgeBlocksRegister.studded_wooden_door_3.get())
                .add(MysticalSteamAgeBlocksRegister.acacia_iron_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.acacia_gold_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.birch_iron_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.birch_gold_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.dark_oak_iron_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.dark_oak_gold_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.jungle_iron_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.jungle_gold_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.oak_iron_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.oak_gold_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.spruce_iron_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.spruce_gold_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_iron_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_gold_studded_block.get())
                .add(MysticalSteamAgeBlocksRegister.acacia_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.birch_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.dark_oak_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.jungle_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.oak_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.spruce_studded_pressure_plate.get());
        tag(BlockTags.LOGS_THAT_BURN)
                .add(MysticalSteamAgeBlocksRegister.baobab_log.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_wood.get());
        tag(BlockTags.LOGS)
                .add(MysticalSteamAgeBlocksRegister.baobab_log.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_wood.get());
        tag(BlockTags.LEAVES)
                .add(MysticalSteamAgeBlocksRegister.baobab_leaves.get());
       /* tag(BlockTags.SAPLINGS)
                .add(MysticalSteamAgeBlocksRegister.baobab_sapling.get());*/
        tag(BlockTags.PLANKS)
                .add(MysticalSteamAgeBlocksRegister.baobab_planks.get());
        tag(BlockTags.WOODEN_DOORS)
                .add(MysticalSteamAgeBlocksRegister.baobab_door.get())
                .add(MysticalSteamAgeBlocksRegister.studded_wooden_door_1.get())
                .add(MysticalSteamAgeBlocksRegister.studded_wooden_door_2.get())
                .add(MysticalSteamAgeBlocksRegister.studded_wooden_door_3.get());
        tag(BlockTags.WOODEN_PRESSURE_PLATES)
                .add(MysticalSteamAgeBlocksRegister.baobab_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.acacia_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.birch_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.dark_oak_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.jungle_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.oak_studded_pressure_plate.get())
                .add(MysticalSteamAgeBlocksRegister.spruce_studded_pressure_plate.get());
        tag(BlockTags.WOODEN_TRAPDOORS)
                .add(MysticalSteamAgeBlocksRegister.baobab_trapdoor.get());
        tag(BlockTags.FENCE_GATES)
                .add(MysticalSteamAgeBlocksRegister.baobab_fence_gate.get());
        tag(BlockTags.WOODEN_BUTTONS)
                .add(MysticalSteamAgeBlocksRegister.baobab_button.get());
        tag(BlockTags.WOODEN_STAIRS)
                .add(MysticalSteamAgeBlocksRegister.baobab_stairs.get());
        tag(BlockTags.WOODEN_SLABS)
                .add(MysticalSteamAgeBlocksRegister.baobab_slab.get());
        tag(BlockTags.WOODEN_FENCES)
                .add(MysticalSteamAgeBlocksRegister.baobab_fence.get());
        tag(BlockTags.MINEABLE_WITH_HOE)
                .add(MysticalSteamAgeBlocksRegister.feather_herb.get())
                .add(MysticalSteamAgeBlocksRegister.feather_herb_block.get())
                .add(MysticalSteamAgeBlocksRegister.camas.get())
                .add(MysticalSteamAgeBlocksRegister.baobab_leaves.get());
        tag(BlockTags.NEEDS_STONE_TOOL)
                .add(MysticalSteamAgeBlocksRegister.tin_block.get())
                .add(MysticalSteamAgeBlocksRegister.zinc_block.get())
                .add(MysticalSteamAgeBlocksRegister.salt_block.get())
                .add(MysticalSteamAgeBlocksRegister.tin_ore.get())
                .add(MysticalSteamAgeBlocksRegister.zinc_ore.get())
                .add(MysticalSteamAgeBlocksRegister.salt_ore.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_sulphur_ore.get())
                .add(MysticalSteamAgeBlocksRegister.deepslate_tin_ore.get());
        tag(BlockTags.NEEDS_IRON_TOOL)
                .add(MysticalSteamAgeBlocksRegister.brass_block.get())
                .add(MysticalSteamAgeBlocksRegister.bronze_block.get())
                .add(MysticalSteamAgeBlocksRegister.devil_iron_block.get())
                .add(MysticalSteamAgeBlocksRegister.steel_block.get())
                .add(MysticalSteamAgeBlocksRegister.nether_devil_iron_ore.get())
                .add(MysticalSteamAgeBlocksRegister.nether_sulphur_ore.get())
                .add(MysticalSteamAgeBlocksRegister.marble.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black.get())
                .add(MysticalSteamAgeBlocksRegister.marble_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_wall.get())
                .add(MysticalSteamAgeBlocksRegister.marble_pillar.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_slab.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_brick.get())
                .add(MysticalSteamAgeBlocksRegister.marble_bricks_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_bricks_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_bricks_wall.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_wall.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_pillar.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_black.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_black_slab.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_black_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_brick.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_bricks_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_bricks_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_bricks_wall.get());
        tag(BlockTags.BEACON_BASE_BLOCKS)
                .add(MysticalSteamAgeBlocksRegister.brass_block.get())
                .add(MysticalSteamAgeBlocksRegister.bronze_block.get())
                .add(MysticalSteamAgeBlocksRegister.tin_block.get())
                .add(MysticalSteamAgeBlocksRegister.zinc_block.get())
                .add(MysticalSteamAgeBlocksRegister.devil_iron_block.get())
                .add(MysticalSteamAgeBlocksRegister.steel_block.get())
                .add(MysticalSteamAgeBlocksRegister.salt_block.get());
        tag(BlockTags.CROPS)
                .add(MysticalSteamAgeBlocksRegister.feather_herb.get())
                .add(MysticalSteamAgeBlocksRegister.camas.get());
        tag(BlockTags.STAIRS)
                .add(MysticalSteamAgeBlocksRegister.marble_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_bricks_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_black_stairs.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_bricks_stairs.get());
        tag(BlockTags.SLABS)
                .add(MysticalSteamAgeBlocksRegister.marble_slab.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_bricks_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_slab.get())
                .add(MysticalSteamAgeBlocksRegister.polished_marble_black_slab.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_bricks_slab.get());
        tag(BlockTags.WALLS)
                .add(MysticalSteamAgeBlocksRegister.marble_wall.get())
                .add(MysticalSteamAgeBlocksRegister.marble_bricks_wall.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_wall.get())
                .add(MysticalSteamAgeBlocksRegister.marble_black_bricks_wall.get());
        tag(BlockTags.FLOWERS)
                .add(MysticalSteamAgeBlocksRegister.dust_flower.get())
                .add(MysticalSteamAgeBlocksRegister.fire_flower.get())
                .add(MysticalSteamAgeBlocksRegister.ice_flower.get())
                .add(MysticalSteamAgeBlocksRegister.irrlicht.get())
                .add(MysticalSteamAgeBlocksRegister.purple_rose.get())
                .add(MysticalSteamAgeBlocksRegister.pink_fern.get())
                .add(MysticalSteamAgeBlocksRegister.star_flower.get())
                .add(MysticalSteamAgeBlocksRegister.white_rose.get())
                .add(MysticalSteamAgeBlocksRegister.camas.get())
                .add(MysticalSteamAgeBlocksRegister.cloud_bush.get())
                .add(MysticalSteamAgeBlocksRegister.fire_bush.get())
                .add(MysticalSteamAgeBlocksRegister.shadow_fern.get())
                .add(MysticalSteamAgeBlocksRegister.silver_umbrella.get());
        tag(BlockTags.FLOWER_POTS)
                .add(MysticalSteamAgeBlocksRegister.potted_dust_flower.get())
                .add(MysticalSteamAgeBlocksRegister.potted_fire_flower.get())
                .add(MysticalSteamAgeBlocksRegister.potted_ice_flower.get())
                .add(MysticalSteamAgeBlocksRegister.potted_irrlicht.get())
                .add(MysticalSteamAgeBlocksRegister.potted_purple_rose.get())
                .add(MysticalSteamAgeBlocksRegister.potted_pink_fern.get())
                .add(MysticalSteamAgeBlocksRegister.potted_star_flower.get())
                .add(MysticalSteamAgeBlocksRegister.potted_white_rose.get());
                //.add(MysticalSteamAgeBlocksRegister.potted_baobab_sapling.get());

    }
}
